model:
  name: point2emb
  num_layers: 4
  hidden_dims: 256
  output_dims: 513  # CLIP dimensions = 512 + SDF = 1

task:
  name: clip_sdf
  dataset: r3d
  dataset_path: "../clip-fields/Kitchen.r3d"
  clip_model: ViT_B_32
  queries:
    - Chair
    - Refrigerator
    - Microwave
    - Trash can
    - Sink
    - Coffee Machine
  rotate_image: true

  finished:
    max_steps: 8000
  dataloader:
    train:
      batch_size: 16
      num_workers: 0
      persistent_workers: false

optimizer:
  name: adam

lr_scheduler:
  name: linear

trainer:
  exp_name: "4_256_no"
  base_run_dir: "usa"
  run_id: 0
  name: sl
  checkpoint:
    save_every_n_steps: 2000
    only_save_most_recent: true
  validation:
    valid_every_n_steps: 250
    num_init_valid_steps: 1

logger:
  - name: stdout
#  - name: tensorboard

launcher:
  name: slurm
  num_nodes: 1
  gpus_per_node: 1
